dist: xenial
osx_image: xcode9.2
language: rust
branches:
  only:
  - master
  - dev
rust:
  - stable
  - nightly
os:
  - linux
  - osx

addons:
  apt:
    sources:
    - sourceline: 'ppa:fish-shell/release-2'
    packages:
    - bash
    - fish
    - python3
    - zsh

env:
  global:
  - RUST_BACKTRACE=1

before_script:
- ./tests/.travis/hack.sh
- eval "$(gimme 1.12)" # golang for 'jump' benchmarks

script:
- cargo build --verbose --examples
- cargo build --release # for integ tests
# integ on stable
# integ-nightly on osx nightly and linux nightly
- MAKE_TARGET="integ"
- 'if [[ "${TRAVIS_RUST_VERSION}" == "nightly" ]]; then MAKE_TARGET=integ-nightly; fi'
- cd tests && make $MAKE_TARGET
