dist: xenial
language: rust
branches:
  only:
  - master
  - dev
rust:
  - stable
  - nightly
os:
  - linux
  - osx

addons:
  apt:
    sources:
    - sourceline: 'ppa:fish-shell/release-2'
    packages:
    - bash
    - fish
    - python3
    - zsh
  homebrew:
    packages:
    - bash
    - fish
    - gimme
    - python3
    - zsh

env:
  global:
  - RUST_BACKTRACE=1

before_script:
- sudo -E ./tests/.travis/hack.sh
- eval "$(gimme 1.11)" # golang for 'jump' benchmarks

script:
- cargo build --verbose --examples
- cargo build --release # for integ tests
- cd tests && make "$([ "${TRAVIS_OS_NAME}-${TRAVIS_RUST_VERSION}" == "linux-nightly" ] && echo integ-all || echo integ)"
