language: rust
branches:
  only:
  - master
  - dev
rust:
  - stable
  - nightly

addons:
  apt:
    packages:
    - zsh
    - bash
    - python3

env:
  global:
  - RUST_BACKTRACE=1

before_script:
- eval "$(gimme 1.11)" # golang for 'jump' benchmarks

script:
- cargo build --verbose --examples
- cargo build --release # for integ tests
- cd tests && make "$([ "${TRAVIS_RUST_VERSION}" == "nightly" ] && echo integ-all || echo integ)"
