sudo: required
language: rust
branches:
  only:
  - master
  - dev
  - "tmp/sema"
rust:
  - stable
  - nightly

addons:
  apt:
    packages:
    - zsh
    - bash
    - python3

env:
  global:
  - RUST_BACKTRACE=1

before_script:
- eval "$(gimme 1.11)" # golang for 'jump' benchmarks

script:
- uname -a
- cat /etc/os-release
- ls -1 /sys/fs/cgroup/
