use std::path::Path;
use harness::autojumpers::Autojumper;
use std::fs;
use std::io::Write;

pub enum Shell {
    Bash,
    Zsh,
    #[allow(dead_code)] Conch,
}

pub struct ShellCmd<'a> {
    pub cmd: &'a str,
    pub env: Vec<(&'a str, String)>,
}

impl Shell {
    pub fn name(&self) -> &'static str {
        match self {
            &Shell::Bash => "bash",
            &Shell::Zsh => "zsh",
            &Shell::Conch => unimplemented!(),
        }
    }

    pub fn from_str(name: &str) -> Self {
        match name {
            "bash" => Shell::Bash,
            "zsh" => Shell::Zsh,
            _ => unimplemented!(),
        }
    }

    pub fn setup(&self, root: &Path, autojump: &Autojumper, ps1: &str, preinit: &str) {
        let rc_file = match *self {
            Shell::Bash | Shell::Zsh => root.join(format!("home/pazi/.{}rc", self.name())),
            Shell::Conch => unimplemented!(),
        };

        let rc_template = match *self {
            Shell::Bash => format!(
                r#"#Autogenerated by pazi integ tests
set -e
{3}
export PS1="{2}" # sep so we know when our commands finished
export PATH=$PATH:$(dirname "{0}")
{1}
"#,
                autojump.bin_path(),
                autojump.init_for(self),
                ps1,
                preinit,
            ),
            Shell::Zsh => format!(
                r#"#Autogenerated by pazi integ tests
set -e
unsetopt zle
export PS1="{2}" # sep so we know when our commands finished
export PATH=$PATH:$(dirname "{0}")
{1}
"#,
                autojump.bin_path(),
                autojump.init_for(self),
                ps1
            ),
            Shell::Conch => unimplemented!(),
        };

        fs::create_dir_all(root.join("home/pazi")).unwrap();
        fs::File::create(rc_file)
            .unwrap()
            .write_all(rc_template.as_bytes())
            .unwrap();
    }

    pub fn command(&self, root: &Path) -> ShellCmd {
        ShellCmd {
            cmd: self.name(),
            env: vec![("HOME", root.join("home/pazi").to_string_lossy().to_string())],
        }
    }
}
